"""
pipeline/clip_description.py

Builds the social-media description (.md) that ships next to each cut clip.

Every description has two sections:

1. A FIXED disclaimer line (same for every clip) asking viewers to watch the
   full service before commenting. The ``******`` is a placeholder for the
   full-sermon link, filled in by hand (or a later pipeline step).

2. A DYNAMIC body generated by Manus AI (``VideoSegment.social_description``):
   opens with a question the full sermon answers, followed by supporting
   verse/commentary pulled from the transcript, ending with ``#shorts``.
"""

from __future__ import annotations

import logging
from pathlib import Path

from models.video_segment import VideoSegment

logger = logging.getLogger(__name__)

# Section 1 — fixed for every clip. ``******`` = full-sermon link placeholder.
FIXED_DESCRIPTION_HEADER = (
    "Pirms komentē, neaizrauj no konteksta, "
    "noklausies visu dievkalpojuma ierakstu: ******"
)

# Fallback dynamic body when Manus did not supply one.
DEFAULT_DYNAMIC_BODY = "#shorts"


def build_clip_description_markdown(segment: VideoSegment) -> str:
    """Compose the full Markdown description for a single clip."""
    dynamic_body = segment.social_description.strip() or DEFAULT_DYNAMIC_BODY

    parts: list[str] = []
    if segment.suggested_title.strip():
        parts.append(f"# {segment.suggested_title.strip()}")
    parts.append(FIXED_DESCRIPTION_HEADER)
    parts.append(dynamic_body)

    return "\n\n".join(parts).rstrip() + "\n"


def write_clip_description_file(
    segment: VideoSegment,
    clip_video_path: Path,
) -> Path:
    """
    Write the clip description to ``<clip stem>.md`` beside the clip video.
    Returns the path written.
    """
    description_path = clip_video_path.with_suffix(".md")
    description_path.parent.mkdir(parents=True, exist_ok=True)
    description_path.write_text(
        build_clip_description_markdown(segment),
        encoding="utf-8",
    )
    logger.info(f"Clip description saved: {description_path}")
    return description_path
